# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull do codigo fonte
      uses: actions/checkout@v2
    - name: Setup do Node.js 16.1.0
      uses: actions/setup-node@v2
      with:
        node-version: 16.1.0
    - name: Executa o NPM CI
      run: npm ci
    - name: Executa o NPM RUN
      run: npm run build --if-present
    - name: Executa o NPM TEST
      run: npm test
    - name: Executa o SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}